# Site settings
title: Schrijven
description: "Tips over het schrijven van een inleiding, nawoord, discussie of conclusie, voor je scriptie, thesis of boek."
baseurl: ""
url: "http://schrijven.gissen.nl"

# Build settings
markdown: kramdown
permalink: pretty
